//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerDetail
    {
        public string RecentJobRole { get; set; }
        public string DurationYears { get; set; }
        public string DurationMonths { get; set; }
        public bool StillInCurrentRole { get; set; }
        public string Resume { get; set; }
        public string CoverLetter { get; set; }
        public bool IsPrivacyDetailsAccepted { get; set; }
        public bool IsDeclarationChecked { get; set; }
        public int Id { get; set; }
    }
}
