//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public string StreetDetails { get; set; }
        public string Suburb { get; set; }
        public string NearestRailwayStation { get; set; }
        public string Postcode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public int Id { get; set; }
    }
}
