//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetail
    {
        public string HighestQualification { get; set; }
        public string GroupCategory { get; set; }
        public DateTime YearOfCompletion { get; set; }
        public string UniversityDetails { get; set; }
        public int Id { get; set; }
    }
}
