USE [master]
GO

/****** Object:  Database [CandidateInfo]    Script Date: 11/06/2015 4:18:54 PM ******/
CREATE DATABASE [CandidateInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CandidateInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CandidateInfo.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CandidateInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CandidateInfo_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CandidateInfo] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CandidateInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CandidateInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CandidateInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CandidateInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CandidateInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CandidateInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [CandidateInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CandidateInfo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CandidateInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CandidateInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CandidateInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CandidateInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CandidateInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CandidateInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CandidateInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CandidateInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CandidateInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CandidateInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CandidateInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CandidateInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CandidateInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CandidateInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CandidateInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CandidateInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CandidateInfo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CandidateInfo] SET  MULTI_USER 
GO

ALTER DATABASE [CandidateInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CandidateInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CandidateInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CandidateInfo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CandidateInfo] SET  READ_WRITE 
GO


